version: "3.5"

services:
  front:
    build:
      context: .
      dockerfile: ./dev.Dockerfile
    ports:
      - 3000:3000
    environment: 
      REACT_APP_GATEWAY: localhost:5000
    volumes:
      - ./src:/app/src
